[build]
  command = "npm run production"
  publish = "dist"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://toot.cafe/.well-known/webfinger?resource=acct:tinyexplosions@toot.cafe"
  status = 200
